name: PictureFrame
author: FlorestanII
main: me.florestanii.pictureframe.PictureFrame
version: VERSION

commands:
  pictureframe:
     descripton: PictureFrame command
     usage: / <commands> <args>
     aliases: [pf]
