name: PictureFrame
author: FlorestanII
main: me.florestanii.pictureframe.PictureFrame
version: VERSION

commands:
  pictureframe:
    descripton: PictureFrame command
    usage: /pictureframe <command> <args>
    aliases: [pf]

permissions:
  pictureframe.create:
    description: Players with this permission may create posters
    default: op
  pictureframe.reload:
    description: Players with this permission may reload the plugin
    default: op
  pictureframe.interact:
    description: Players with this permission may interact with maps of posters (i.e. rotate them)
    default: op
  pictureframe.destroy:
    description: Players with this permission may destroy posters
    default: op
